import os
import sys
import io
import subprocess
from dotenv import load_dotenv


# Path logic for absolute reliability during demo
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from rich import print
from backend.core.agent import SysMindAgent

def main():
    """
    SysMind Agent Runner (Titanium Edition).
    Entry point for the Grand Prize demo scenario.
    """
    # Grand Prize Hardening: Force UTF-8 for Windows Terminal stability
    if sys.platform == "win32":
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

    print(r"""[bold cyan]
   _____            __  __ _           _ 
  / ____|          |  \/  (_)         | |
 | (___  _   _ ___ | \  / |_ _ __   __| |
  \___ \| | | / __|| |\/| | | '_ \ / _` |
  ____) | |_| \__ \| |  | | | | | | (_| |
 |_____/ \__, |___/|_|  |_|_|_| |_|\__,_|
          __/ |  TITANIUM EDITION v1.4                  
         |___/   [dim]Powered by Gemini 3[/dim]
[/bold cyan]""")
    print("-" * 50)
    
    load_dotenv()
    
    try:
        # Defaults to 'sysmind-target' as per default config
        target_name = os.environ.get("TARGET_CONTAINER", "sysmind-target")
        agent = SysMindAgent(target_name=target_name)
        
        if agent.connect():
            # GRAND PRIZE SCENARIO: Multimodal SRE + Precision Remediation
            # We assume 'dashboard_cpu_spike.png' has been generated by the chaos test setup
            # Grand Prize: Real-Time Telemetry Injection
            # Instead of just a text prompt, we feed the agent LIVE metrics
            metrics = "N/A"
            try:
                res = subprocess.run(
                    ["docker", "stats", agent.target_name, "--no-stream", "--format", "{{.CPUPerc}} / {{.MemPerc}}"], 
                    capture_output=True, text=True
                )
                metrics = res.stdout.strip()
            except: pass

            objective = (
                f"ALERT: Operations dashboard reports critical instability. "
                f"Analyze system state. Dashboard shows CPU spike. "
                f"LIVE METRICS [{agent.target_name}]: {metrics}. "
                f"Identify root cause and mitigate. "
                "STEP 1: Analyze the visual dashboard 'dashboard_cpu_spike.png' to identify the anomaly type and timing. "
                "STEP 2: Verify the root cause in the system (check processes or logs). "
                "STEP 3: Remediate the issue safely and verify the system is stable."
            )
            
            agent.ooda_loop(objective)
        else:
            print("[FAIL] Aborting: Target environment unreachable.")
            
    except KeyboardInterrupt:
        print("\n[bold yellow]👋 Monitoring session terminated by user. Shutting down safely...[/bold yellow]")
        sys.exit(0)
    except Exception as e:
        print(f"\n[FATAL ERROR] {e}")

if __name__ == "__main__":
    main()
